"""Agregando nuevos atributos de una de las tablas

Revision ID: bfc8015670f0
Revises: f15dccb48568
Create Date: 2023-09-20 17:35:25.133026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfc8015670f0'
down_revision = 'f15dccb48568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbldetPrestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPrestamo', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cuota', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idPrestamo'], ['tblprestamo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tbldetprestamo')
    with op.batch_alter_table('tblprestamo', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tblprestamo', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    op.create_table('tbldetprestamo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('idPrestamo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('cuota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idPrestamo'], ['tblprestamo.id'], name='tbldetprestamo_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tbldetPrestamo')
    # ### end Alembic commands ###
