"""Agregando nuevos atributos a la tabla Cliente

Revision ID: f15dccb48568
Revises: 6a632cab9adf
Create Date: 2023-09-20 17:16:16.698619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15dccb48568'
down_revision = '6a632cab9adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tblprestamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idPrestamista', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tasa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('montoPrestado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tblprestamista', ['idPrestamista'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tblprestamo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('total')
        batch_op.drop_column('montoPrestado')
        batch_op.drop_column('tasa')
        batch_op.drop_column('fecha')
        batch_op.drop_column('idPrestamista')

    # ### end Alembic commands ###
